import argparse


def get_args():
    arg = argparse.ArgumentParser()
    arg.add_argument('-dataset', type=str, default='DB15K')
    arg.add_argument('-batch_size', type=int, default=1024)
    arg.add_argument('-margin', type=float, default=8.0)
    arg.add_argument('-dim', type=int, default=250)
    arg.add_argument('-epoch', type=int, default=1000)
    arg.add_argument('-save', type=str, default='./checkpoint/model.pth')
    arg.add_argument('-img_dim', type=int, default=4096)
    arg.add_argument('-neg_num', type=int, default=64)
    arg.add_argument('-learning_rate', type=float, default=0.0001)
    arg.add_argument('-lrg', type=float, default=0.001)
    arg.add_argument('-lrd', type=float, default=0.001)
    arg.add_argument('-adv_temp', type=float, default=2.0)
    arg.add_argument('-visual', type=str, default='random')
    arg.add_argument('-max_neighbor', type=int, default=8)
    arg.add_argument('-seed', type=int, default=42)
    arg.add_argument('-missing_rate', type=float, default=0.8)
    arg.add_argument('-postfix', type=str, default='')
    arg.add_argument('-con_temp', type=float, default=0)
    arg.add_argument('-lamda', type=float, default=0.0001)
    arg.add_argument('-modal_align_rate', type=float, default=0.0002)
    arg.add_argument('-mu', type=float, default=0.0001)
    arg.add_argument('-adv_num', type=int, default=1)
    arg.add_argument('-disen_weight', type=float, default=0.01)
    arg.add_argument('-miss_type', type=str, default=None)
    arg.add_argument('-miss_prop', type=float, default=None)
    arg.add_argument('-weight_decay', type=float, default=0.00001)
    arg.add_argument('-metric', type=str, default='hit1')
    arg.add_argument('-metric_delta', type=float, default=0.0001)
    arg.add_argument('-metric_patience', type=int, default=5)
    arg.add_argument('-lr_decay_patience', type=int, default=1)
    arg.add_argument('-lr_decay_factor', type=float, default=0.1)
    arg.add_argument('-loss_early_stop_patience', type=int, default=50)
    return arg.parse_args()


if __name__ == "__main__":
    args = get_args()
    print(args)